__Câu 1. Giảm chiều dữ liệu (2 điểm)__
<br> Tập tin Phan_lop.csv chứa những mẫu dữ liệu phân lớp các đối tượng thuộc về một trong 6 loại (class): 0..5, dựa trên 12 thuộc tính f1..f12 của đối tượng. 
<br> 1.1) Áp dụng phương pháp giảm chiều của dữ liệu để số chiều thấp hơn so với dữ liệu gốc. 
<br> 1.2) Số chiều được giảm còn lại bao nhiêu ? Giải thích nguyên nhân/cơ sở về số chiều được giảm? 

In [9]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('Phan_lop.csv')
data.head()

f1         f2        f3        f4        f5        f6         f7  \
0 -2.403589  -0.218339 -3.015506  2.187585 -1.415101 -0.000049   2.920957   
1 -0.922966   6.564721  8.542600 -3.676891  1.526910 -6.132242  -1.284702   
2  9.381326  -0.157043  9.674137  4.059390  9.150245 -8.320246  10.076978   
3 -7.610665 -10.375051  0.398027 -6.178855  5.848558  2.276540  -1.726164   
4  8.586239  -4.265564  4.788978  4.309953  2.938052 -4.294121   6.980088   

          f8         f9       f10       f11       f12  Class  
0  -4.165317  -2.237563  1.567810  4.056278 -5.816942      3  
1  -7.841047  10.161966 -1.933277  8.959247 -2.492584      4  
2 -11.596349  -2.900057 -1.890156  0.390029 -5.383296      0  
3   9.378226   1.146725 -9.630693 -8.620247 -0.552103      2  
4  -9.878268  -5.017204  0.154492  7.647917 -1.004416      0

In [5]:
data.shape

(1000, 13)

In [8]:
X = data[['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12']]
X.head()

f1         f2        f3        f4        f5        f6         f7  \
0 -2.403589  -0.218339 -3.015506  2.187585 -1.415101 -0.000049   2.920957   
1 -0.922966   6.564721  8.542600 -3.676891  1.526910 -6.132242  -1.284702   
2  9.381326  -0.157043  9.674137  4.059390  9.150245 -8.320246  10.076978   
3 -7.610665 -10.375051  0.398027 -6.178855  5.848558  2.276540  -1.726164   
4  8.586239  -4.265564  4.788978  4.309953  2.938052 -4.294121   6.980088   

          f8         f9       f10       f11       f12  
0  -4.165317  -2.237563  1.567810  4.056278 -5.816942  
1  -7.841047  10.161966 -1.933277  8.959247 -2.492584  
2 -11.596349  -2.900057 -1.890156  0.390029 -5.383296  
3   9.378226   1.146725 -9.630693 -8.620247 -0.552103  
4  -9.878268  -5.017204  0.154492  7.647917 -1.004416

__Using Decomposition SVD = U,s,VT__

In [10]:
U, s, VT = np.linalg.svd(X)

In [17]:
U[:5]

array([[ 0.0081356 , -0.00882084, -0.00914671, ...,  0.01199833,
         0.0321645 , -0.03305347],
       [ 0.02260871, -0.01633934, -0.03260737, ..., -0.00791646,
         0.0440831 ,  0.01340946],
       [ 0.05442033, -0.0176625 , -0.0210221 , ...,  0.00476702,
         0.01797315, -0.01214796],
       [-0.00243459,  0.05958895,  0.01566827, ...,  0.03684704,
         0.00191968, -0.02905699],
       [ 0.03655345, -0.02705951, -0.00197082, ...,  0.01093627,
         0.02196915, -0.00180254]])

In [12]:
s

array([393.98522644, 360.47791006, 244.61171415, 204.75879654,
       146.57940798,  83.75887418,  67.18145391,  64.24942167,
        63.22026205,  62.35396961,  59.96919522,  57.86974355])

In [15]:
VT[:5]

array([[ 0.10748425, -0.17774397,  0.36613003,  0.04229405,  0.38211945,
        -0.04277679,  0.4322055 , -0.57324393,  0.03350547, -0.29034071,
         0.09948995, -0.2498806 ],
       [-0.50668937, -0.4324574 ,  0.07658845, -0.28957046,  0.2020109 ,
         0.02039637,  0.0168541 ,  0.32409424,  0.05168404, -0.30799405,
        -0.46539518, -0.0765496 ],
       [ 0.20639278, -0.18791069, -0.43915012,  0.03557623,  0.26599237,
         0.57199276, -0.02485931, -0.15352737,  0.01321706, -0.25385539,
        -0.02302028,  0.49062167],
       [-0.13014557, -0.03793983, -0.26592812,  0.3179543 , -0.20388403,
         0.28258634,  0.34414128, -0.04260743, -0.59648339,  0.13071938,
        -0.25088985, -0.36374706],
       [ 0.55837462, -0.1686288 ,  0.18490923,  0.04140706,  0.18054471,
        -0.31313319,  0.12985393,  0.43784175, -0.46314499, -0.1134188 ,
        -0.08545533,  0.22358486]])

__NHẬN XÉT__
<br> Từ ma trận s, ta thấy rằng hệ số từ lambda1 đến lambda5 có giá trị lớn hơn rất nhiều so với các giá trị từ lambda6 trở đi
<br> => Choose n_componts = 5

In [21]:
Sigma = np.zeros(X.shape)
Sigma[:X.shape[1],:X.shape[1]] = np.diag(s)
Sigma[:5]

array([[393.98522644,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        , 360.47791006,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , 244.61171415,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , 204.75879654,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        146.57940798,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ]])

In [18]:
n_components = 5

In [23]:
Sigma = Sigma[:,:n_components]
VT = VT[:n_components,:]

In [24]:
Sigma

array([[393.98522644,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        , 360.47791006,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        , 244.61171415,   0.        ,
          0.        ],
       ...,
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ]])

In [25]:
VT

array([[ 0.10748425, -0.17774397,  0.36613003,  0.04229405,  0.38211945,
        -0.04277679,  0.4322055 , -0.57324393,  0.03350547, -0.29034071,
         0.09948995, -0.2498806 ],
       [-0.50668937, -0.4324574 ,  0.07658845, -0.28957046,  0.2020109 ,
         0.02039637,  0.0168541 ,  0.32409424,  0.05168404, -0.30799405,
        -0.46539518, -0.0765496 ],
       [ 0.20639278, -0.18791069, -0.43915012,  0.03557623,  0.26599237,
         0.57199276, -0.02485931, -0.15352737,  0.01321706, -0.25385539,
        -0.02302028,  0.49062167],
       [-0.13014557, -0.03793983, -0.26592812,  0.3179543 , -0.20388403,
         0.28258634,  0.34414128, -0.04260743, -0.59648339,  0.13071938,
        -0.25088985, -0.36374706],
       [ 0.55837462, -0.1686288 ,  0.18490923,  0.04140706,  0.18054471,
        -0.31313319,  0.12985393,  0.43784175, -0.46314499, -0.1134188 ,
        -0.08545533,  0.22358486]])

In [26]:
## Option 1
T_s1 = U.dot(Sigma)
T_s1[:5]

array([[  3.20530596,  -3.17971957,  -2.23739179,   5.92758746,
         -4.26093755],
       [  8.90749875,  -5.88997044,  -7.97614417, -13.37725242,
         -7.40919568],
       [ 21.44080721,  -6.36693971,  -5.14225184,   0.59137322,
          8.03081602],
       [ -0.95919135,  21.48049851,   3.83264189,  -1.80841538,
          2.71718236],
       [ 14.40151868,  -9.75435666,  -0.48208519,   1.61120289,
          6.46202209]])

In [29]:
## Option 2
T_s2 = X.dot(VT.T)
T_s2.columns=['comp1','comp2','comp3','comp4','comp5']
T_s2['Class']=data['Class']
T_s2[:5]

comp1      comp2     comp3      comp4     comp5  Class
0   3.205306  -3.179720 -2.237392   5.927587 -4.260938      3
1   8.907499  -5.889970 -7.976144 -13.377252 -7.409196      4
2  21.440807  -6.366940 -5.142252   0.591373  8.030816      0
3  -0.959191  21.480499  3.832642  -1.808415  2.717182      2
4  14.401519  -9.754357 -0.482085   1.611203  6.462022      0

__NHẬN XÉT__
<br> Sau khi giảm thì dữ liệu còn lại 5 chiều (so với dữ liệu gốc là 12 chiều)

In [32]:
from sklearn.decomposition import PCA
pca = PCA(5)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [33]:
pca.components_

array([[ 6.65018582e-02,  2.97551242e-01, -3.67779107e-01,
         3.26867355e-02, -4.14005389e-01,  2.26503909e-02,
        -4.20279922e-01,  4.60787392e-01, -3.66049402e-02,
         3.52461999e-01,  6.16431684e-02,  2.81850230e-01,
        -3.20673680e-02],
       [-4.57918765e-01, -3.65000866e-01, -2.73992902e-02,
        -3.33113833e-01,  1.18200362e-01,  2.66203434e-03,
        -1.28006866e-01,  5.09218334e-01,  8.19868306e-02,
        -2.62091904e-01, -4.17484373e-01,  7.69592358e-02,
         8.47418805e-03],
       [ 1.96406770e-01, -1.69762269e-01, -4.48234185e-01,
         6.58685918e-02,  2.45789078e-01,  5.92752327e-01,
        -1.18015810e-02, -1.95461379e-01, -5.41953755e-04,
        -2.24850738e-01, -2.36124595e-02,  4.56953773e-01,
         1.31598366e-01],
       [ 4.86389012e-02,  9.23820842e-02,  2.40838415e-01,
        -2.56472048e-01,  1.71657223e-01, -1.76269701e-01,
        -3.74679157e-01, -1.53977504e-01,  6.83468619e-01,
        -4.19596682e-02,  2.47758907e

In [34]:
pca.components_.shape

(5, 13)

In [35]:
pca.explained_variance_

array([150.14738749, 115.78706074,  60.48001203,  37.14189827,
        19.21975368])

In [36]:
pca.explained_variance_.shape

(5,)

In [37]:
#transform data
B = pca.transform(data)
B

array([[ -0.69221135,  -1.07000504,  -2.19177319,  -6.57038468,
          7.95112534],
       [ -4.78178657,  -3.43734637,  -8.4477533 ,  13.11779736,
          6.22026452],
       [-16.69240508,  -8.5429408 ,  -5.75130709,  -3.19940755,
         -7.70677881],
       ...,
       [ -2.89915665,  -7.05538976,   3.33613763,  -5.88241572,
          6.34403495],
       [ -4.65170029,  -4.68454531,  15.531988  ,   7.0605433 ,
         -0.7358818 ],
       [ -4.63014062,  22.0272588 ,  -2.3228671 ,  -2.04138719,
          0.48595074]])

In [38]:
pca.explained_variance_ratio_

array([0.36588393, 0.28215359, 0.14737962, 0.09050856, 0.04683531])

In [39]:
principalDf = pd.DataFrame(data = B, columns = ['comp1','comp2','comp3','comp4','comp5'])
principalDf.head()

comp1      comp2     comp3      comp4     comp5
0  -0.692211  -1.070005 -2.191773  -6.570385  7.951125
1  -4.781787  -3.437346 -8.447753  13.117797  6.220265
2 -16.692405  -8.542941 -5.751307  -3.199408 -7.706779
3  -3.687761  24.972640  2.060657  -3.227896  0.416217
4  -8.926874  -9.483645 -1.072485  -4.167949 -5.233570

In [40]:
T_s2

comp1      comp2      comp3      comp4     comp5  Class
0     3.205306  -3.179720  -2.237392   5.927587 -4.260938      3
1     8.907499  -5.889970  -7.976144 -13.377252 -7.409196      4
2    21.440807  -6.366940  -5.142252   0.591373  8.030816      0
3    -0.959191  21.480499   3.832642  -1.808415  2.717182      2
4    14.401519  -9.754357  -0.482085   1.611203  6.462022      0
5     6.571545  -7.258012  16.148735  -5.902067  0.333435      5
6     9.882369  -3.265388 -11.008753 -12.335477 -0.094997      4
7     6.136374  -3.956829   0.700267   7.851271 -2.645695      3
8     3.321929  17.001892   0.666948   1.015207  4.323445      2
9     6.229348  -8.641288  21.925908  -4.590605  0.930717      5
10   -2.522725  20.533129   3.563205  -2.380262  6.935187      2
11    0.952316  21.420601   1.041191  -2.067556  3.537851      2
12    4.141084  -7.344655  17.063612  -1.842546  0.493929      5
13    6.202828  -6.143770  -5.153226 -13.197021 -3.191578      4
14  -16.995469 -15.295234   1.033345  -4.460797  3.812218      1
15    6.373318  -2.854362   0.509922   8.408561 -4.353325      3
16    7.890407  -4.497240  -7.319873 -11.764082 -2.812317      4
17   -2.097512  16.832341   0.312886  -4.608882  2.613696      2
18    2.706379  19.391411  -0.107018  -5.464492  6.489176      2
19   10.429795  -9.185112  14.853872  -1.376287 -0.464942      5
20    9.913533 -10.773509  16.025550  -3.335054 -1.997601      5
21   20.340122  -8.818139  -5.197232   2.786637  7.857878      0
22   20.412415 -13.034137  -7.701675  -1.242263  7.723437      0
23  -23.565658 -14.742786  -1.851934  -1.397726  2.724763      1
24    4.502399  -5.758940  -1.361726   4.456511 -0.886484      3
25   -0.594772  21.959793   1.821249  -3.220666  1.590805      2
26   10.855116  -2.858417  -6.758361 -11.148464 -3.408666      4
27    7.990417  -8.939067  19.770065  -2.594501  0.592748      5
28   -0.054189  18.459187   1.736072  -8.489394  4.593821      2
29   10.740762  -5.109359  -5.266161 -14.208023 -4.074005      4
..         ...        ...        ...        ...       ...    ...
970  11.452481  -1.005221  -4.285394 -14.682793 -6.696219      4
971   4.263386  -8.607909   0.801075   9.633910 -4.687010      3
972   6.322886  -4.908349  17.057739  -4.868275 -0.710508      5
973   5.665012  -5.180460  17.241359  -2.466736  3.450670      5
974   0.979071  17.055583   0.562144  -4.368149  3.569193      2
975 -25.021680 -14.220668  -3.990075  -2.313569  4.322136      1
976  18.884460 -14.965942  -2.765708   6.142845  9.889501      0
977  -1.989185  15.154426   2.313806  -3.052824  5.130134      2
978   2.073250  18.265939  -4.036988  -2.855147  1.998059      2
979   7.470371  -6.720949  -5.414866 -13.643477 -2.085254      4
980  10.770425  -6.897061  -5.965392 -12.222346 -4.408192      4
981   0.281037  18.809524   1.904176  -3.469420  5.395006      2
982   7.115301  -2.489354  -4.545403  -9.760230 -3.689350      4
983   9.062392  -7.625187  16.364805  -1.552954  2.902800      5
984   8.025467  -7.959004  -5.094919 -12.845773 -2.538535      4
985   1.463458  15.229714   3.583005  -3.486563  2.657354      2
986   9.286663  -4.195192  18.052678  -4.088303 -1.129823      5
987   5.000254  -5.702251   0.070996   5.497838 -4.407119      3
988 -19.527338 -15.362295   4.322845  -4.761410  3.727846      1
989  11.032505  -7.099305  16.386601  -5.536734  3.339987      5
990  16.961706 -11.765930 -10.785392   2.231770  6.096440      0
991  15.963847 -10.767930  -5.695844   2.286844  7.710197      0
992  18.676157  -7.920115  -4.912731   3.665315  9.882121      0
993 -17.845802 -13.335218  -5.769680  -2.345968  6.194140      1
994   5.799553  -5.587695   0.225919   9.407524 -1.572039      3
995   6.621316  -4.038036  -7.128144 -10.267855 -3.526737      4
996   2.456810  17.440938   0.485116  -0.615886  1.685514      2
997   7.247628  -8.487553   3.099554   6.003105 -3.793704      3
998   9.397251  -7.681111  15.952583  -7.455595 -1.084527      5
999   0.990669  18.745230  -0.557641  -3.358